version: '3'
services:
  backed:
    build: node
    image: node-express-dev:1.0
    tty: true
    volumes:
      - ./:/app
    ports:
      - "4000:3000"
  fronted:
    build: vue
    ports:
      - 3000:8080
    volumes:
      - ./fronted:/app
    stdin_open: true
    tty: true